### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by RhysAM** [Dijana181/SQL-Capstone-project#1]
I appreciate how you left some comments at the beginning of your queries to indicate what you were doing but later on you stopped! It's best practice to leave lots and lots of comments, so either you or someone else can quickly debug errors. A lot of what you do is hard to decipher because of it!

**Comment by Dijana181** [comment]
Ok, didn't realise that I'd done this until reviewing my code. I understand where you're coming from though , it helps to document the logic.
