### ISSUE TITLE
Calculating Churn Rate

### ISSUE THREAD

**Issue by RhysAM** [Dijana181/SQL-Capstone-project#2]
I see that you calculated the churn rates for both the segments, and then the segments combined. There's no real reason to do this! If you see the data is separated into two segments, as you did, calculations done on aggregations of the two are pretty much meaningless. I'm just saying this because in larger datasets, doing all that extra work could be extremely computationally expensive!

**Comment by Dijana181** [comment]
Ah ok- I see. Noted for next time
