### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by RhysAM** [Dijana181/SQL-Capstone-project#3]
## Rubric Score
 
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_  3.8
* _Comment(s):_ Every answer uses text and query results as support for the conclusions. Conclusions are very clear and are all grounded in real statistical data. Your slides, however, are EXTREMELY information dense, so I'd recommend breaking them up into more slides, so you don't overload the viewer. Also, I think you could've used a better font color for some of your information! Bright yellow is kinda jarring. 
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4
* _Comment(s):_ All queries accurately retrieve the data intended. Great work writing some of those complex queries. All I suggest is more commenting, so your more complex queries can be easily understood.
 
### Criteria 3: Query Formatting
* _Score Level:_ 4
* _Comment(s):_ Queries are formatted according to the linked style guide. Great job indenting and using alias names. One area for improvement is to not calculate churn rates for the data in aggregate, like I suggested. 
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4
* _Comment(s):_ Report demonstrates clear understanding​ of churn rates. Terms are used​ correctly throughout the report. Your conclusion to focus on Segment 30 is well supported by the evidence!

 ### Overall Score: 15.8/16
Fantastic work! Overall, very good job! Your presentation is very well made and demonstrates a clear understanding of how the SQL tables relate Codeflix's real-world business problems. You did a great job writing the complex queries necessary to retrieve all the results. A few additional improvements I can point to. For the month by month analysis with the two segment's churn rates, you used a bar graph to track differences. I would suggest using a line graph, so you can more easily demonstrate the differences between the two. Overall, though, you provided a thorough explanation of your findings and communicated these findings clearly to an outside audience. Excellent work!

**Comment by Dijana181** [comment]
Noted, thanks for the feedback. I feel that I have learnt a great deal by working through the Learn SQL from Scratch course. I enjoyed working on this project, and yes agreed- the yellow font wasn't particularly reader friendly.
